/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// It is committed here as a placeholder so `tsc --noEmit` has something to
// work with before the first build runs. Do not edit by hand — once you run
// `npm run dev` or `npm run build`, Next.js will regenerate it and it should
// stay gitignored from that point on (see .gitignore).
